### ISSUE TITLE
teamshop无法更改比默认少一阶

### ISSUE THREAD

**Issue by EndMoyu** [TheRamU/BedwarsScoreBoardAddon#9]
如题，但标题没描述好
teamshop 只要比默认config少写了一阶就会报错且不能正常使用
出现在2.12.0以上，但是2.10.2就没有这样的问题（同样报错但是仍可以正常使用）

![Screenshot_20211228-125200_PojavLauncher（适用于 Android 的《Minecraft：Java版》）](https://user-images.githubusercontent.com/85435560/147529878-f9fab2d8-32a9-4564-969f-dc1744ae4e48.png)
![Screenshot_20211228-125613_PojavLauncher（适用于 Android 的《Minecraft：Java版》）](https://user-images.githubusercontent.com/85435560/147529881-db67da37-e49c-4320-94ad-6414c9e3b82f.png)
以下是log，原谅我刚使用Github..
[12:51:58] [Server thread/ERROR]: Could not pass event InventoryClickEvent to BedwarsScoreBoardAddon v2.13.1
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1633) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_281]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_281]
	at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:771) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:710) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:613) [PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_281]
Caused by: java.lang.NullPointerException
	at me.ram.bedwarsscoreboardaddon.addon.teamshop.TeamShop.isEnough(TeamShop.java:582) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.addon.teamshop.TeamShop.getStateValue(TeamShop.java:675) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.addon.teamshop.TeamShop.getStateColor(TeamShop.java:652) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.addon.teamshop.TeamShop.setTeamShopItem(TeamShop.java:184) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.addon.teamshop.TeamShop.updateTeamShop(TeamShop.java:266) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.addon.teamshop.TeamShop.onClick(TeamShop.java:362) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.arena.Arena.onClick(Arena.java:297) ~[?:?]
	at me.ram.bedwarsscoreboardaddon.listener.EventListener.onClick(EventListener.java:290) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_281]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_281]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_281]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[PaperSpigot-1.8.8.jar:git-PaperSpigot-f6fba00-9935adc]
	... 15 more

上次issues属实弱智..

**Comment by EndMoyu** [comment]
另外，队伍资源只有铁和金是写死的吗？
